[[plugins]]
# カーソル位置のコンテキストのfile typeを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]]
# カーソル位置のコンテキストに合わせてfile typeを切り替える
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
# 補完機能
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.config/nvim/plugins/neocomplete.rc.vim
'''
