# Tips
# hook_addはプラグイン追加後
# hook_sourceはプラグイン読み込み前
# hook_post_sourceはプラグイン読み込み後

[[plugins]]
# プラグイン管理
repo = 'Shougo/dein.vim'

# ==========================================================
# filer
# ==========================================================

#[[plugins]]
# 統合インターフェース
#repo = 'Shougo/denite.nvim'
#if = "has('nvim')"

[[plugins]]
# 統合インターフェース
repo = 'Shougo/unite.vim'
#if = "!has('nvim')"
hook_add = '''
nnoremap <silent> fb :<C-u>Unite buffer<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
#if = "!has('nvim')"
depends = 'unite.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''

[[plugins]]
# 重い作業時の非同期処理
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# ==========================================================
# basic
# ==========================================================

[[plugins]]
# 補完 nvim用
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
# 楽にコメントアウト
repo = 'scrooloose/nerdcommenter'
hook_add = '''
source ~/.config/nvim/plugins/nerdcomenter.rc.vim
'''

#[[plugins]]
# 背景透過
#repo = 'miyakogi/seiya.vim'
#hook_add = '''
#let g:seiya_auto_enable=1
#'''

[[plugins]]
# toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
# カッコを自動で閉じる
repo = 'Townk/vim-autoclose'

[[plugins]]
# 貼り付け時に自動でペーストモードにする
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
# 非同期処理
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

# ==========================================================
# linter
# ==========================================================

[[plugins]]
repo = 'neomake/neomake'
if = "has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/neomake.rc.vim
'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
if = "!has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/syntastic.rc.vim
'''

# ==========================================================
# terminal
# ==========================================================

[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/neoterm.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimshell'
if = "!has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/vimshell.rc.vim
'''

# ==========================================================
# colorscheme
# ==========================================================

#[[plugins]]
#repo = 'tomasr/molokai'
#hook_add = '''
#  source ~/.config/nvim/plugins/molokai.rc.vim
#'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.config/nvim/plugins/iceberg.rc.vim
'''

# ==========================================================
# airline
# ==========================================================

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
source ~/.config/nvim/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
let g:airline_theme='luna'
'''

[[plugins]]
repo = 'enricobacis/vim-airline-clock'

[[plugins]]
repo = 'Zuckonit/vim-airline-tomato'
hook_add = '''
let g:tomato#lang = 'english'
'''

[[plugins]]
repo = 'mattn/webapi-vim'
hook_add = '''
let g:weather#area = 'hokkaido,japan'
'''

[[plugins]]
repo = 'Wildog/airline-weather.vim'


# ==========================================================
# other
# ==========================================================

[[plugins]]
# にゃーん
repo = 'rtakasuke/vim-neko'
hook_add = '''
source ~/.config/nvim/plugins/vim-neko.rc.vim
'''

[[plugins]]
# カレンダー
repo = 'itchyny/calendar.vim'
